const $=s=>document.querySelector(s),screen=$('#screen');
const models=[['萌趣小黄鸭','玩具','独家',1.2,'单个部件',12800,3205,'黄色 / 橙色'],['太空小宇航员','玩具','精选',3.2,'多个部件',8632,2860,'白色 / 蓝色'],['霸王龙模型','玩具','独家',2.6,'单个部件',4521,1819,'绿色'],['梦幻城堡','套件','精选',4.8,'多个部件',3906,2341,'粉色 / 蓝色 / 白色'],['卡通小飞机','套件','精选',2.1,'多个部件',2853,1920,'蓝色 / 白色'],['招财猫摆件','摆件','独家',3.4,'单个部件',6724,3891,'白色 / 红色'],['剑龙模型','玩具','精选',1.8,'单个部件',3140,1508,'蓝色 / 橙色'],['消防车模型','套件','精选',5.2,'多个部件',4280,2036,'红色 / 白色']].map((m,id)=>({id,name:m[0],cat:m[1],tag:m[2],hours:m[3],parts:m[4],prints:m[5],likes:m[6],colors:m[7]}));
let state={page:'home',channel:'全部',filter:null,query:'',likes:new Set(),history:[],account:'小小创客',saved:0,lessonScroll:0,forced:'',banner:0,paused:false};let stack=[],draft={},timer,recordStart=0;
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function fit(){let mobile=innerWidth<=650,scale=mobile?innerWidth/941:Math.min(.62,(innerWidth-(innerWidth<=900?270:460))/941);scale=Math.max(.25,scale);$('#stage').style.width=941*scale+'px';$('#stage').style.height=1672*scale+'px';$('#phone').style.transform=`scale(${scale})`;}
addEventListener('resize',fit);fit();
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(timer);timer=setTimeout(()=>$('#toast').style.display='none',2200);}
function close(){ $('#overlay').innerHTML=''; }
function modal(body){$('#overlay').innerHTML=`<div class="shade" onclick="if(event.target===this)close()"><section class="sheet" role="dialog" aria-modal="true"><div class="handle"></div><button class="close" aria-label="关闭" onclick="close()">×</button>${body}</section></div>`;}
function push(page,id){stack.push({page:state.page,id:state.id,scroll:screen.scrollTop,query:state.query,forced:state.forced});state.page=page;state.id=id;state.forced='';render();screen.scrollTop=0;}
function back(){close();let p=stack.pop();if(p){Object.assign(state,p);render();screen.scrollTop=p.scroll}else home();}
function home(){close();state.page='home';state.forced='';stack=[];render();screen.scrollTop=state.saved;}
function header(title,right=''){return `<div class="bar"><button class="round" aria-label="返回" onclick="back()">‹</button><h2>${title}</h2>${right||'<span style="width:68px"></span>'}</div>`}
function nav(){ $('#nav').style.display=state.page==='detail'?'none':'flex';$('#nav').innerHTML=[['⌂','模型库','home'],['▣','工作台','work'],['✧','创作','create'],['♙','我的','mine']].map(([i,t,p])=>`<button class="${state.page===p||p==='home'&&!['work','create','mine'].includes(state.page)?'active':''}" onclick="${p==='home'?'home()':`push('${p}')`}"><b>${i}</b>${t}</button>`).join('');document.querySelector('.actions')?.remove();}
function card(m){return `<article class="card" tabindex="0" role="button" aria-label="查看${m.name}" onclick="push('detail',${m.id})" onkeydown="if(event.key==='Enter')push('detail',${m.id})"><div class="photo"><img src="assets/model${m.id}.jpg" alt="${m.name}"><span class="tag">${m.tag}</span><button class="heart ${state.likes.has(m.id)?'on':''}" aria-label="${state.likes.has(m.id)?'取消收藏':'收藏'}${m.name}" onclick="event.stopPropagation();like(${m.id})">${state.likes.has(m.id)?'♥':'♡'}</button></div><div class="cardbody"><h3>${m.name}</h3><p class="time">◷ ${m.hours} 小时 · ${m.parts}</p><div class="meta"><span>Ugee · 官方</span><span>↓ ${(m.prints/1000).toFixed(1)}k &nbsp;<i class="orange">♥</i> ${m.likes+(state.likes.has(m.id)?1:0)}</span></div></div></article>`}
function like(id){state.likes.has(id)?state.likes.delete(id):state.likes.add(id);let pos=screen.scrollTop;render();screen.scrollTop=pos;toast(state.likes.has(id)?'已收藏，喜欢的模型收好啦':'已取消收藏');}
function list(){let a=[...models];if(state.filter){let f=state.filter;a=a.filter(m=>(!f.tags.length||f.tags.includes(m.tag))&&(!f.parts||m.parts===f.parts)&&m.hours>=f.min&&m.hours<=f.max)}else if(state.channel!=='全部'&&state.channel!=='热门'){a=a.filter(m=>state.channel==='精选'?m.tag==='精选':m.cat===state.channel)}if(state.channel==='热门')a.sort((a,b)=>b.prints-a.prints);return a;}
function empty(title,desc,action,label){return `<div class="empty"><span class="symbol">⌕</span><h2>${title}</h2><p>${desc}</p><button class="primary" onclick="${action}">${label}</button></div>`}
function render(){nav();$('#top').style.display='none';let h='';
if(state.page==='home'){let a=list();h=`<div class="bar"><button class="filter" onclick="filters()">⚑ ${state.filter?'已筛选':'筛选'}⌄</button><span class="wordmark">ugee Maker</span><button class="round" aria-label="搜索模型" onclick="push('search')">⌕</button></div><div class="content"><button class="hero" onclick="push('activity')"><img id="banner" src="assets/banner${state.banner?'2':''}.jpg" alt="3D打印，让想象力发光，点击参与活动"></button><div class="dots"><button class="${!state.banner?'active':''}" aria-label="第一个活动" onclick="banner(0)"></button><button class="${state.banner?'active':''}" aria-label="第二个活动" onclick="banner(1)"></button></div><div class="entrances"><button onclick="push('lessons');screen.scrollTop=state.lessonScroll"><img src="assets/tutorial.jpg" alt="教程指南"></button><button onclick="community()"><img src="assets/community.jpg" alt="社区"></button></div><div class="channels" id="channels">${['全部','热门','精选','玩具','套件'].map(x=>`<button class="chip ${state.channel===x?'active':''}" onclick="channel('${x}')">${x}</button>`).join('')}</div>${state.filter?`<p class="smallnote">筛选结果 · ${state.filter.min}–${state.filter.max} 小时 <button class="filter" onclick="state.filter=null;render()">清除 ×</button></p>`:''}${state.forced==='load'?empty('模型暂时没加载出来','网络开了个小差，再试一次吧。',"state.forced='';render()",'重新加载'):state.forced==='filterEmpty'||!a.length?empty('还没找到这样的模型','试试放宽打印时长，或减少筛选条件。','filters()','调整筛选'):`<div class="grid">${a.map(card).join('')}</div><p class="smallnote" style="text-align:center;margin:35px">已经看到全部模型啦</p>`}</div>`;}
if(state.page==='search'||state.page==='results'){h=`<div class="bar"><button class="round" onclick="back()" aria-label="返回">‹</button><form class="searchbox" onsubmit="event.preventDefault();search($('#query').value)"><input id="query" aria-label="搜索模型" placeholder="想找什么模型？" value="${esc(state.query)}"><button type="button" aria-label="语音输入" onclick="voice()">♩</button></form><button class="filter" onclick="search($('#query').value)">搜索</button></div><div class="content">`;if(state.page==='search'){h+=`${state.history.length?`<h3 class="sectiontitle">◷ 最近搜索 <button onclick="state.history=[];render()">清空</button></h3><div class="row">${(state.expanded?state.history:state.history.slice(0,3)).map(t=>`<button class="chip" data-query="${esc(t)}" onclick="search(this.dataset.query)">${esc(t.length>12?t.slice(0,12)+'…':t)}</button>`).join('')}${state.history.length>3?'<button class="chip" onclick="state.expanded=!state.expanded;render()">⌄</button>':''}</div>`:''}<h3 class="sectiontitle">🔥 大家都在搜 <small class="muted">本周榜单</small></h3>${['恐龙','小动物','宇航员','礼物','城堡'].map((x,i)=>`<button class="rank" onclick="search('${x}')"><b>${i+1}</b><img src="assets/model${[2,0,1,5,3][i]}.jpg" alt=""><strong>${x}</strong><span>›</span></button>`).join('')}`;}else{let q=state.query;let a=models.filter(m=>(m.name+m.cat+m.tag+m.colors).includes(q)||q==='小动物'&&[0,5].includes(m.id)||q==='恐龙'&&[2,6].includes(m.id)||q.includes('礼物')&&[0,3,5].includes(m.id));h+=`<p class="muted">“${esc(q)}”的搜索结果</p>${state.forced==='searchEmpty'||!a.length?empty('还没找到这个模型','换个词试试，比如“恐龙”或“小动物”。',"state.page='search';state.query='';state.forced='';render()",'重新搜索'):`<p class="smallnote">找到 ${a.length} 个模型</p><div class="grid">${a.map(card).join('')}</div>`}`;}h+='</div>';}
if(state.page==='detail'){let m=models[state.id];h=header('模型详情',`<button class="round ${state.likes.has(m.id)?'orange':''}" aria-label="收藏" onclick="like(${m.id})">${state.likes.has(m.id)?'♥':'♡'}</button>`)+`<div class="content"><img class="detailpic" src="assets/model${m.id}.jpg" alt="${m.name}"><h1 class="detailtitle">${m.name}</h1><p class="muted">Ugee Maker · 官方模型</p><div class="box stats"><div><strong>${(m.prints*2.3/1000).toFixed(1)}k</strong><small>查看</small></div><div><strong>${(m.prints/1000).toFixed(1)}k</strong><small>打印</small></div><div><strong>${m.likes+(state.likes.has(m.id)?1:0)}</strong><small>点赞 / 收藏</small></div></div><div class="box"><h3>模型介绍</h3><p>把喜欢的${m.name.replace('模型','')}带到你的桌面！一起动手，让小小的创意变成摸得到的快乐。</p><div class="row"><span class="chip">${m.cat}</span><span class="chip">${m.tag}</span></div></div><div class="box"><h3>▣ 打印信息</h3>${[['预计时长',m.hours+' 小时'],['模型尺寸',m.id===3?'128 × 96 × 110 mm':'65 × 52 × 70 mm'],['耗材颜色',m.colors],['部件类型',m.parts],['分盘打印',m.parts==='多个部件'?'3 盘':'1 盘']].map(([a,b])=>`<div class="spec"><span>${a}</span><b>${b}</b></div>`).join('')}</div><div class="box"><h3>精选评论</h3><div class="comment">🌟 糖果小公主<small>打印出来好可爱，已经放在书桌上啦！</small></div><div class="comment">🚀 小小设计师<small>和爸爸一起完成的，很有成就感。</small></div></div><h3 class="sectiontitle">你可能还喜欢</h3><div class="grid">${models.filter(x=>x.id!==m.id).sort((a,b)=>Number(b.cat===m.cat)-Number(a.cat===m.cat)).slice(0,4).map(card).join('')}</div></div>`;let ac=document.createElement('div');ac.className='actions';ac.innerHTML=`<button class="secondary" onclick="push('editor',${m.id})">⚙ 打印设置</button><button class="primary" onclick="push('work',${m.id})">▣ 立即打印</button>`;$('#phone').append(ac);}
if(state.page==='lessons'){let lessons=['打印机连接教程','首次打印设置','喷头校准教程','平台调平教程','更换耗材教程','常见问题排查'];let q=state.lessonQuery||'';let shown=lessons.filter(x=>x.includes(q));if(state.lessonType==='图文')shown=shown.filter(x=>x==='常见问题排查');if(state.lessonType==='视频')shown=shown.filter(x=>x!=='常见问题排查');if(state.lessonSort==='热门')shown.reverse();h=header('教程指南')+`<div class="content"><form class="searchbox" onsubmit="event.preventDefault();state.lessonQuery=$('#lq').value;render()"><input id="lq" placeholder="搜索教程" value="${esc(q)}"><button aria-label="搜索教程">⌕</button></form><div class="row" style="margin:25px 0"><select class="chip" aria-label="教程排序" onchange="state.lessonSort=this.value;render()"><option ${state.lessonSort!=='热门'?'selected':''}>最新</option><option ${state.lessonSort==='热门'?'selected':''}>热门</option></select>${['全部','视频','图文'].map(t=>`<button class="chip ${(state.lessonType||'全部')===t?'active':''}" onclick="state.lessonType='${t}';render()">${t}</button>`).join('')}</div>${shown.length?shown.map((t,i)=>`<button class="lesson" onclick="push('lesson','${t}')"><img src="assets/model${i%8}.jpg" alt=""><div><h3>${t}</h3><p>${t==='常见问题排查'?'图文指南':'▷ 视频教程'} · ${i+2} 分钟</p></div><span>›</span></button>`).join(''):empty('没有找到相关教程','换个关键词或切换内容类型。',"state.lessonQuery='';state.lessonType='全部';render()",'查看全部教程')}</div>`;}
if(state.page==='lesson'){h=header('教程详情')+`<div class="content"><h1 class="detailtitle">${esc(state.id)}</h1><p class="muted">Ugee Maker 官方 · 使用指南</p><div class="box"><h3>开始之前</h3><p>请和家长一起准备好设备，并检查打印平台是否整洁。</p></div>${['打开设备并检查连接','在模型库选择喜欢的模型','进入工作台，确认后开始打印'].map((t,i)=>`<div class="box"><h3><span class="orange">0${i+1}</span> ${t}</h3><p>${['将打印机放在平稳位置，按照设备说明完成连接。','查看模型的预计时长、耗材颜色与分盘数量。','设备状态、耗材与打印任务的检查将在工作台完成。'][i]}</p></div>`).join('')}<p class="muted">当前为教程交互示例，正式图文与视频由后台配置。</p></div>`;}
if(state.page==='work'||state.page==='editor'||state.page==='create'){let edit=state.page==='editor';h=header(edit?'打印设置':state.page==='create'?'创作':'工作台')+`<div class="content">${state.id!==undefined&&typeof state.id==='number'?`<div class="box"><img style="width:100%;border-radius:22px" src="assets/model${state.id}.jpg" alt="${models[state.id].name}"><h2>${models[state.id].name}</h2></div>`:''}<div class="empty" style="padding-top:65px"><span class="symbol">${edit?'⚙':'▣'}</span><h2>${edit?'已进入 3D 模型编辑入口':state.page==='create'?'让创意继续生长':'已进入工作台'}</h2><p>${edit?'后续在此调整模型与打印设置。':state.page==='create'?'创作模块由其他页面承接。':'设备连接、耗材检查与打印确认<br>将在工作台完成。'}</p><button class="primary" onclick="back()">返回模型库流程</button></div></div>`;}
if(state.page==='mine'){h=header('我的')+`<div class="content"><div class="box row"><div class="account">☺</div><div><h2>${state.account}</h2><button class="filter" onclick="accounts()">切换账号 ⌄</button></div></div><h3 class="sectiontitle">我的收藏 · ${state.likes.size}</h3>${state.likes.size?`<div class="grid">${models.filter(m=>state.likes.has(m.id)).map(card).join('')}</div>`:empty('喜欢的模型，放在这里','点击模型上的爱心，就能收好它。','home()','去发现模型')}</div>`;}
if(state.page==='activity'){h=header('灵感小乐园')+`<div class="content"><img style="width:100%;border-radius:28px" src="assets/banner2.jpg" alt="春日创意挑战赛"><h2 class="detailtitle">让想象力发光</h2><p class="muted">挑选一个喜欢的模型，开启今天的创意挑战。</p><div class="grid">${models.slice(0,4).map(card).join('')}</div></div>`;}
screen.innerHTML=h;}
function channel(c){state.channel=c;state.filter=null;state.forced='';let p=screen.scrollTop;render();screen.scrollTop=p;}
function search(q){q=q.trim();if(!q){toast('先输入想找的模型吧');return}if(state.page==='search')stack.push({page:'search',scroll:0,query:q,forced:''});state.page='results';state.query=q;state.filter=null;state.forced='';state.history=[q,...state.history.filter(x=>x!==q)].slice(0,12);close();render();screen.scrollTop=0;}
function filters(){draft=state.filter?JSON.parse(JSON.stringify(state.filter)):{tags:[],parts:'',min:1,max:12};drawFilter();}
function drawFilter(){modal(`<h2>找到喜欢的模型</h2><h3>模型标签 <small class="muted">可多选</small></h3><div class="row">${['独家','精选'].map(x=>`<button class="chip ${draft.tags.includes(x)?'active':''}" onclick="draft.tags.includes('${x}')?draft.tags=draft.tags.filter(t=>t!=='${x}'):draft.tags.push('${x}');drawFilter()">${x==='独家'?'★':'✦'} ${x}</button>`).join('')}</div><h3>部件复杂度</h3><div class="row">${['单个部件','多个部件'].map(x=>`<button class="chip ${draft.parts===x?'active':''}" onclick="draft.parts=draft.parts==='${x}'?'':'${x}';drawFilter()">${x}</button>`).join('')}</div><h3>打印时长 <strong id="rangeLabel" class="orange">${draft.min}–${draft.max} 小时</strong></h3><label class="muted">最短时长<input aria-label="最短打印时长" type="range" min="1" max="12" value="${draft.min}" oninput="draft.min=Math.min(+this.value,draft.max);this.value=draft.min;$('#rangeLabel').textContent=draft.min+'–'+draft.max+' 小时'"></label><label class="muted">最长时长<input aria-label="最长打印时长" type="range" min="1" max="12" value="${draft.max}" oninput="draft.max=Math.max(+this.value,draft.min);this.value=draft.max;$('#rangeLabel').textContent=draft.min+'–'+draft.max+' 小时'"></label><div class="row" style="justify-content:space-between"><span class="muted">1 小时</span><span class="muted">12 小时</span></div><div class="row" style="margin-top:40px"><button class="secondary" onclick="draft={tags:[],parts:'',min:1,max:12};drawFilter()">重置</button><button class="primary" style="flex:1" onclick="applyFilter()">应用筛选</button></div>`);}
function applyFilter(){state.filter=JSON.parse(JSON.stringify(draft));state.channel='全部';state.query='';state.forced='';state.page='home';close();render();screen.scrollTop=530;}
function voice(mode=''){modal(`<h2>说出你想找的模型</h2><div style="text-align:center">${mode==='permission'?`<div class="empty" style="padding:40px"><span class="symbol">♩</span><h2>需要开启麦克风权限</h2><p>开启后，就能说出想找的模型啦。</p><button class="primary" onclick="toast('演示：麦克风权限已开启');voice()">开启麦克风</button></div>`:mode==='recognition'?`<div class="empty" style="padding:40px"><span class="symbol">♩</span><h2>刚才没有听清</h2><p>靠近一点，再说一次吧。</p><button class="primary" onclick="voice()">重新说话</button></div>`:`<p class="muted" id="voiceLabel">长按说话，松手结束</p><button class="voiceorb" aria-label="长按说话" onpointerdown="recordStart=Date.now();this.classList.add('recording');$('#voiceLabel').textContent='正在听，松手结束…';this.setPointerCapture(event.pointerId)" onpointerup="finishVoice()" onpointercancel="voice()">♩</button><p class="muted">试着说：“我想打印一只恐龙”</p><p class="smallnote">演示语音将识别为“恐龙”</p>`}<button class="secondary wide" onclick="close();if(!['search','results'].includes(state.page))push('search');$('#query').focus()">改用文字输入</button></div>`);}
function finishVoice(){if(Date.now()-recordStart<250){voice('recognition');return}$('#voiceLabel').textContent='正在识别…';setTimeout(()=>search('恐龙'),550);}
function community(){modal('<h2>前往 Ugee 社区</h2><p class="muted">社区将通过浏览器打开 Web 端精选内容。</p><p class="muted">当前原型尚未配置正式社区地址。</p><button class="primary wide" onclick="close()">知道了</button>');}
const accountLikes={};function accounts(){modal(`<h2>选择你的账号</h2>${['小小创客','星星探险家','家长账号'].map(x=>`<button class="secondary wide" onclick="accountLikes[state.account]=new Set(state.likes);state.account='${x}';state.likes=accountLikes['${x}']||new Set();close();render();toast('已切换账号')">☺ ${x} ${state.account===x?'✓':''}</button>`).join('')}`);}
function banner(i){state.banner=i;let img=$('#banner');if(img)img.src=`assets/banner${i?'2':''}.jpg`;document.querySelectorAll('.dots button').forEach((b,n)=>b.classList.toggle('active',n===i));}
setInterval(()=>{if(state.page==='home'&&!state.paused&&!$('#overlay').innerHTML)banner(1-state.banner)},5000);
let touchX=0;screen.addEventListener('touchstart',e=>touchX=e.touches[0].clientX,{passive:true});screen.addEventListener('touchend',e=>{if(e.target.closest('.hero')&&Math.abs(e.changedTouches[0].clientX-touchX)>30)banner(1-state.banner)},{passive:true});
screen.addEventListener('scroll',()=>{if(state.page==='home'){state.saved=screen.scrollTop;state.paused=screen.scrollTop>10;$('#top').style.display=screen.scrollTop>10&&$('#channels')?'block':'none'}if(state.page==='lessons')state.lessonScroll=screen.scrollTop;});
function goTop(){screen.scrollTo({top:0,behavior:'smooth'});state.paused=false;}
function resetDemo(){state.channel='全部';state.filter=null;state.query='';state.saved=0;state.forced='';$('#scenario').value='';home();screen.scrollTop=0;}
function demo(t){close();if(!t)return;if(t==='permission'||t==='recognition'){push('search');voice(t);return}if(t==='searchEmpty'){push('results');state.query='会飞的西瓜';state.forced=t;}else{home();state.forced=t;if(t==='filterEmpty'){state.filter={tags:['独家'],parts:'多个部件',min:10,max:12};state.channel='全部'}}render();screen.scrollTop=t==='searchEmpty'?0:560;}
render();

if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'search_models',description:'在原型中搜索模型并显示结果',inputSchema:{type:'object',properties:{query:{type:'string',minLength:1}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.query!=='string'||!input.query.trim())throw new Error('请输入搜索词');search(input.query);return {query:state.query,page:state.page}}})).catch(()=>{});}catch{}}
